default_context:
  _pegasus_version: '2022.12'
  author_name: Jared Black
  ci: github_actions
  css_framework: bulma
  css_theme: default
  database: postgres
  deploy_platform: render
  description: Finance website with calculators to support decision making.
  domain_name: finmako.com
  email: jaredblackjcb@gmail.com
  enable_google_login: y
  enable_twitter_login: n
  front_end_framework: htmx
  project_name: finmako
  project_slug: finmako
  stripe_payment_mode: checkout
  subscription_billing_model: default
  use_2fa: y
  use_api_keys: n
  use_docker: n
  use_impersonation: y
  use_sentry: y
  use_subscriptions: y
  use_teams: n
  use_translations: y
  use_wagtail: y
