services:
  - type: web
    name: finmako
    env: python
    buildCommand: "./deploy/build.sh"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT --workers 1 --threads 8 --timeout 0 finmako.wsgi:application"
    region: oregon
    plan: free
    numInstances: 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.14
      - key: DJANGO_SETTINGS_MODULE
        value: finmako.settings_production
      - key: DJANGO_DATABASE_NAME
        fromDatabase:
          name: finmako
          property: database
      - key: DJANGO_DATABASE_USER
        fromDatabase:
          name: finmako
          property: user
      - key: DJANGO_DATABASE_PASSWORD
        fromDatabase:
          name: finmako
          property: password
      - key: DJANGO_DATABASE_HOST
        fromDatabase:
          name: finmako
          property: host
      - key: DJANGO_DATABASE_PORT
        fromDatabase:
          name: finmako
          property: port
      - key: REDIS_HOST
        fromService:
          type: redis
          name: finmako-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: finmako-redis
          property: port
      - key: SECRET_KEY
        sync: false
      - key: GOOGLE_ANALYTICS_ID
        sync: false
      - key: STRIPE_LIVE_PUBLIC_KEY
        sync: false
      - key: STRIPE_LIVE_SECRET_KEY
        sync: false
      - key: DJSTRIPE_WEBHOOK_SECRET
        sync: false
      - key: SENTRY_DSN
        sync: false

# Celery task worker (not available on 'free' plan)
#  - type: worker
#    name: finmako_celery
#    env: python
#    buildCommand: "./deploy/build_celery.sh"
#    startCommand: celery -A finmako worker -l INFO --beat --concurrency 2
#    region: oregon
#    plan: starter
#    numInstances: 1
#    envVars:
#      - key: PYTHON_VERSION
#        value: 3.9.14
#      - key: DJANGO_SETTINGS_MODULE
#        value: finmako.settings_production
#      - key: DJANGO_DATABASE_NAME
#        fromDatabase:
#          name: finmako
#          property: database
#      - key: DJANGO_DATABASE_USER
#        fromDatabase:
#          name: finmako
#          property: user
#      - key: DJANGO_DATABASE_PASSWORD
#        fromDatabase:
#          name: finmako
#          property: password
#      - key: DJANGO_DATABASE_HOST
#        fromDatabase:
#          name: finmako
#          property: host
#      - key: DJANGO_DATABASE_PORT
#        fromDatabase:
#          name: finmako
#          property: port
#      - key: REDIS_HOST
#        fromService:
#          type: redis
#          name: finmako-redis
#          property: host
#      - key: REDIS_PORT
#        fromService:
#          type: redis
#          name: finmako-redis
#          property: port
#      - key: SECRET_KEY
#        sync: false
#      - key: GOOGLE_ANALYTICS_ID
#        sync: false
#      - key: STRIPE_LIVE_PUBLIC_KEY
#        sync: false
#      - key: STRIPE_LIVE_SECRET_KEY
#        sync: false
#      - key: DJSTRIPE_WEBHOOK_SECRET
#        sync: false
#      - key: SENTRY_DSN
#        sync: false

# Redis instance (for celery and caching)
  - type: redis
    name: finmako-redis
    ipAllowList: []
    plan: free

# Postgres database
databases:
  - name: finmako
    plan: free
    databaseName: finmako
    user: finmako
    ipAllowList: [] # only allow internal connections
